### ISSUE TITLE
Strange lines get inserted in the wrong place or diff computed wrong

### ISSUE THREAD

**Issue by jackanderson** [ace-diff/ace-diff#28] opened 2018-02-23 00:51 UTC
Im not sure what is causing the issue, but ive seen several cases where doing a copy actually results in new differences. ive attached two files that you can paste into the respective editors. copy the difference in the fileb  side to the filea side and you'll see a new difference is then created for the blank line after the original difference.  Not sure if this is line ending related or diff related?

[fileb.txt](https://github.com/ace-diff/ace-diff/files/1750084/fileb.txt)
[filea.txt](https://github.com/ace-diff/ace-diff/files/1750085/filea.txt)

**Comment by JackuB** [comment] 2018-02-25 10:11
I _think_ I know how to fix, but I’m currently travelling so I could get to it in a few days.

**Comment by jackanderson** [comment] 2018-02-26 18:29
hmm. nope. that didnt fix the issue. I still get a new difference after copying. It's like it's not initially detecting the blank line as a difference and then once the first difference is resolved then it detects it as a difference.

**Comment by JackuB** [comment] 2018-03-08 02:11
Still travelling, but managed to create the smallest possible repro:

```
start

something else

end
```

and

```
starts
mid
end
```

I will be looking into why this is happening. Pushed the branch here for now https://github.com/ace-diff/ace-diff/tree/JackuB/merge-with-newlines

**Comment by JackuB** [comment] 2018-04-19 15:55
The issue is with newlines - if you look at the raw output from https://github.com/JackuB/diff-match-patch there is `\nend` (`0` means no change, so it's not part of the patch that's applied)
<img width="335" alt="snimek obrazovky 2018-04-19 v 17 04 16" src="https://user-images.githubusercontent.com/1788727/39003140-878fa57a-43fa-11e8-9e75-747c09910491.png">

If you manually move the `\n` to the previous line https://github.com/ace-diff/ace-diff/commit/42b957ee183c614494a614d836f8c8ed1b49d411 it would fix the diffing, as now the newline will be part of the patch.

![2018-04-19 17_52_12](https://user-images.githubusercontent.com/1788727/39003244-be0efde4-43fa-11e8-89c9-31cb7f4a2ddc.gif)

I think it might be related to this behaviour: https://github.com/ace-diff/ace-diff/blob/42b957ee183c614494a614d836f8c8ed1b49d411/src/index.js#L494-L497

**Comment by jackanderson** [comment] 2018-04-19 21:46
any idea what the solution might be?

**Closed** 2018-05-08 12:17 UTC
